name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests=2.31.0
  - pip=23.3.2
  - mlflow=2.10.0
  - hydra-core=1.3.2
  - pip:
      - wandb==0.16.2
      - hydra-joblib-launcher==1.2.0
